/**
 * 強化されたAI対話記録のメタデータ型定義
 */

export interface EnhancedSessionMetadata {
  // 基本情報
  source: string
  originalTimestamp: string

  // プロジェクト情報
  project?: string
  projectPath?: string
  currentFile?: string

  // トピック分類
  topic?: string
  subtopic?: string
  category: SessionCategory

  // 対話分析
  questionType: 'how-to' | 'evaluation' | 'debugging' | 'general' | 'request'
  complexity: 'simple' | 'medium' | 'complex'

  // 解決状況
  resolved: boolean
  followUpNeeded: boolean
  actionItems?: string[]

  // 統計情報
  totalMessages: number
  userMessageCount: number
  assistantMessageCount: number
  totalCharacters: number
  codeBlocks: number

  // スマートタグ
  tags: string[]
  autoGeneratedTags: string[]

  // 要約・検索用
  summary?: string
  keywords: string[]

  // 関連性
  relatedSessions?: string[]
  suggestedActions?: string[]

  // タイトル生成情報
  titleGeneration?: {
    confidence: 'high' | 'medium' | 'low'
    autoGenerated: boolean
    fallbackUsed: boolean
  }
}

export type SessionCategory =
  | 'development' // 開発・実装
  | 'debugging' // バグ・トラブルシューティング
  | 'design' // 設計・アーキテクチャ
  | 'testing' // テスト・品質保証
  | 'deployment' // デプロイ・運用
  | 'learning' // 学習・調査
  | 'consultation' // 相談・アドバイス
  | 'other' // その他

export interface EnhancedSession {
  id: string
  title: string
  startTime: string
  endTime?: string
  metadata: EnhancedSessionMetadata
  messages: EnhancedMessage[]
}

export interface EnhancedMessage {
  id: string
  timestamp: string
  role: 'user' | 'assistant' | 'system'
  content: string
  metadata: {
    sessionId: string
    source: string
    originalTimestamp?: string
    codeBlocks?: CodeBlock[]
    mentions?: string[] // ファイル・技術・ツール等の言及
    intent?: MessageIntent
  }
}

export interface CodeBlock {
  language: string
  code: string
  lineCount: number
  complexity: 'simple' | 'medium' | 'complex'
}

export type MessageIntent =
  | 'question' // 質問
  | 'request' // 依頼・要求
  | 'explanation' // 説明・回答
  | 'code_review' // コードレビュー
  | 'suggestion' // 提案・アドバイス
  | 'confirmation' // 確認
  | 'other' // その他

/**
 * メタデータ生成用のユーティリティ型
 */
export interface MetadataGenerationContext {
  projectPath?: string
  currentWorkingDirectory?: string
  gitRepository?: string
  recentFiles?: string[]
  timestamp: Date
}
